name: Kameron Perkins
favicon: null
layout_spectrum: 0.6212565547320992
typography_spectrum: 0.10504016513004899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7941252167802304
  lightness: 0.8891551792621613
  saturation: 0.5009643204975873
  rhythmicContrast: 0.5769264521077275
purpose: []
